/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfwpstring from './OneOfwpstring';

/**
 * The Project model module.
 * @module model/Project
 * @version 1.0.0
 */
class Project {
    /**
     * Constructs a new <code>Project</code>.
     * @alias module:model/Project
     * @param projectTitle {String} 
     * @param projectStartDate {String} 
     * @param pimage {String} 
     * @param projectDuration {Number} 
     * @param grantAgreement {String} 
     * @param projectEndDate {String} 
     * @param projectAbstract {String} 
     * @param wpproject {module:model/OneOfwpstring} 
     */
    constructor(projectTitle, projectStartDate, pimage, projectDuration, grantAgreement, projectEndDate, projectAbstract, wpproject) { 
        
        Project.initialize(this, projectTitle, projectStartDate, pimage, projectDuration, grantAgreement, projectEndDate, projectAbstract, wpproject);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, projectTitle, projectStartDate, pimage, projectDuration, grantAgreement, projectEndDate, projectAbstract, wpproject) { 
        obj['ProjectTitle'] = projectTitle;
        obj['ProjectStartDate'] = projectStartDate;
        obj['pimage'] = pimage;
        obj['ProjectDuration'] = projectDuration;
        obj['GrantAgreement'] = grantAgreement;
        obj['ProjectEndDate'] = projectEndDate;
        obj['ProjectAbstract'] = projectAbstract;
        obj['wpproject'] = wpproject;
    }

    /**
     * Constructs a <code>Project</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Project} obj Optional instance to populate.
     * @return {module:model/Project} The populated <code>Project</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Project();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('ProjectTitle')) {
                obj['ProjectTitle'] = ApiClient.convertToType(data['ProjectTitle'], 'String');
            }
            if (data.hasOwnProperty('ProjectStartDate')) {
                obj['ProjectStartDate'] = ApiClient.convertToType(data['ProjectStartDate'], 'String');
            }
            if (data.hasOwnProperty('pimage')) {
                obj['pimage'] = ApiClient.convertToType(data['pimage'], 'String');
            }
            if (data.hasOwnProperty('ProjectDuration')) {
                obj['ProjectDuration'] = ApiClient.convertToType(data['ProjectDuration'], 'Number');
            }
            if (data.hasOwnProperty('GrantAgreement')) {
                obj['GrantAgreement'] = ApiClient.convertToType(data['GrantAgreement'], 'String');
            }
            if (data.hasOwnProperty('ProjectEndDate')) {
                obj['ProjectEndDate'] = ApiClient.convertToType(data['ProjectEndDate'], 'String');
            }
            if (data.hasOwnProperty('ProjectAbstract')) {
                obj['ProjectAbstract'] = ApiClient.convertToType(data['ProjectAbstract'], 'String');
            }
            if (data.hasOwnProperty('wpproject')) {
                obj['wpproject'] = ApiClient.convertToType(data['wpproject'], OneOfwpstring);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Project.prototype['_id'] = undefined;

/**
 * @member {String} ProjectTitle
 */
Project.prototype['ProjectTitle'] = undefined;

/**
 * @member {String} ProjectStartDate
 */
Project.prototype['ProjectStartDate'] = undefined;

/**
 * @member {String} pimage
 */
Project.prototype['pimage'] = undefined;

/**
 * @member {Number} ProjectDuration
 */
Project.prototype['ProjectDuration'] = undefined;

/**
 * @member {String} GrantAgreement
 */
Project.prototype['GrantAgreement'] = undefined;

/**
 * @member {String} ProjectEndDate
 */
Project.prototype['ProjectEndDate'] = undefined;

/**
 * @member {String} ProjectAbstract
 */
Project.prototype['ProjectAbstract'] = undefined;

/**
 * @member {module:model/OneOfwpstring} wpproject
 */
Project.prototype['wpproject'] = undefined;






export default Project;

