/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProjectPImage from './ProjectPImage';
import Workpackage from './Workpackage';

/**
 * The Project model module.
 * @module model/Project
 * @version 1.0.0
 */
class Project {
    /**
     * Constructs a new <code>Project</code>.
     * @alias module:model/Project
     * @param pImage {module:model/ProjectPImage} 
     * @param pTitle {String} 
     * @param pStart {String} 
     * @param pWebsite {String} 
     * @param pEnd {String} 
     * @param pDuration {String} 
     * @param pGA {String} 
     * @param pAbstract {String} 
     * @param pDescription {String} 
     * @param pWorkpackage {Array.<module:model/Workpackage>} 
     */
    constructor(pImage, pTitle, pStart, pWebsite, pEnd, pDuration, pGA, pAbstract, pDescription, pWorkpackage) { 
        
        Project.initialize(this, pImage, pTitle, pStart, pWebsite, pEnd, pDuration, pGA, pAbstract, pDescription, pWorkpackage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pImage, pTitle, pStart, pWebsite, pEnd, pDuration, pGA, pAbstract, pDescription, pWorkpackage) { 
        obj['pImage'] = pImage;
        obj['pTitle'] = pTitle;
        obj['pStart'] = pStart;
        obj['pWebsite'] = pWebsite;
        obj['pEnd'] = pEnd;
        obj['pDuration'] = pDuration;
        obj['pGA'] = pGA;
        obj['pAbstract'] = pAbstract;
        obj['pDescription'] = pDescription;
        obj['pWorkpackage'] = pWorkpackage;
    }

    /**
     * Constructs a <code>Project</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Project} obj Optional instance to populate.
     * @return {module:model/Project} The populated <code>Project</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Project();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('pImage')) {
                obj['pImage'] = ProjectPImage.constructFromObject(data['pImage']);
            }
            if (data.hasOwnProperty('pTitle')) {
                obj['pTitle'] = ApiClient.convertToType(data['pTitle'], 'String');
            }
            if (data.hasOwnProperty('pStart')) {
                obj['pStart'] = ApiClient.convertToType(data['pStart'], 'String');
            }
            if (data.hasOwnProperty('pWebsite')) {
                obj['pWebsite'] = ApiClient.convertToType(data['pWebsite'], 'String');
            }
            if (data.hasOwnProperty('pEnd')) {
                obj['pEnd'] = ApiClient.convertToType(data['pEnd'], 'String');
            }
            if (data.hasOwnProperty('pDuration')) {
                obj['pDuration'] = ApiClient.convertToType(data['pDuration'], 'String');
            }
            if (data.hasOwnProperty('pGA')) {
                obj['pGA'] = ApiClient.convertToType(data['pGA'], 'String');
            }
            if (data.hasOwnProperty('pAbstract')) {
                obj['pAbstract'] = ApiClient.convertToType(data['pAbstract'], 'String');
            }
            if (data.hasOwnProperty('pDescription')) {
                obj['pDescription'] = ApiClient.convertToType(data['pDescription'], 'String');
            }
            if (data.hasOwnProperty('pWorkpackage')) {
                obj['pWorkpackage'] = ApiClient.convertToType(data['pWorkpackage'], [Workpackage]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Project.prototype['_id'] = undefined;

/**
 * @member {module:model/ProjectPImage} pImage
 */
Project.prototype['pImage'] = undefined;

/**
 * @member {String} pTitle
 */
Project.prototype['pTitle'] = undefined;

/**
 * @member {String} pStart
 */
Project.prototype['pStart'] = undefined;

/**
 * @member {String} pWebsite
 */
Project.prototype['pWebsite'] = undefined;

/**
 * @member {String} pEnd
 */
Project.prototype['pEnd'] = undefined;

/**
 * @member {String} pDuration
 */
Project.prototype['pDuration'] = undefined;

/**
 * @member {String} pGA
 */
Project.prototype['pGA'] = undefined;

/**
 * @member {String} pAbstract
 */
Project.prototype['pAbstract'] = undefined;

/**
 * @member {String} pDescription
 */
Project.prototype['pDescription'] = undefined;

/**
 * @member {Array.<module:model/Workpackage>} pWorkpackage
 */
Project.prototype['pWorkpackage'] = undefined;






export default Project;

