/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Task model module.
 * @module model/Task
 * @version 1.0.0
 */
class Task {
    /**
     * Constructs a new <code>Task</code>.
     * @alias module:model/Task
     * @param tName {String} 
     * @param tStart {String} 
     * @param tEnd {String} 
     * @param tPMs {String} 
     * @param tDescription {String} 
     */
    constructor(tName, tStart, tEnd, tPMs, tDescription) { 
        
        Task.initialize(this, tName, tStart, tEnd, tPMs, tDescription);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tName, tStart, tEnd, tPMs, tDescription) { 
        obj['tName'] = tName;
        obj['tStart'] = tStart;
        obj['tEnd'] = tEnd;
        obj['tPMs'] = tPMs;
        obj['tDescription'] = tDescription;
    }

    /**
     * Constructs a <code>Task</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Task} obj Optional instance to populate.
     * @return {module:model/Task} The populated <code>Task</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Task();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('tName')) {
                obj['tName'] = ApiClient.convertToType(data['tName'], 'String');
            }
            if (data.hasOwnProperty('tStart')) {
                obj['tStart'] = ApiClient.convertToType(data['tStart'], 'String');
            }
            if (data.hasOwnProperty('tEnd')) {
                obj['tEnd'] = ApiClient.convertToType(data['tEnd'], 'String');
            }
            if (data.hasOwnProperty('tPMs')) {
                obj['tPMs'] = ApiClient.convertToType(data['tPMs'], 'String');
            }
            if (data.hasOwnProperty('tDescription')) {
                obj['tDescription'] = ApiClient.convertToType(data['tDescription'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Task.prototype['_id'] = undefined;

/**
 * @member {String} tName
 */
Task.prototype['tName'] = undefined;

/**
 * @member {String} tStart
 */
Task.prototype['tStart'] = undefined;

/**
 * @member {String} tEnd
 */
Task.prototype['tEnd'] = undefined;

/**
 * @member {String} tPMs
 */
Task.prototype['tPMs'] = undefined;

/**
 * @member {String} tDescription
 */
Task.prototype['tDescription'] = undefined;






export default Task;

