/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Workpackage model module.
 * @module model/Workpackage
 * @version 1.0.0
 */
class Workpackage {
    /**
     * Constructs a new <code>Workpackage</code>.
     * @alias module:model/Workpackage
     * @param wName {String} 
     * @param wPMs {String} 
     * @param wRole {String} 
     */
    constructor(wName, wPMs, wRole) { 
        
        Workpackage.initialize(this, wName, wPMs, wRole);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, wName, wPMs, wRole) { 
        obj['wName'] = wName;
        obj['wPMs'] = wPMs;
        obj['wRole'] = wRole;
    }

    /**
     * Constructs a <code>Workpackage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Workpackage} obj Optional instance to populate.
     * @return {module:model/Workpackage} The populated <code>Workpackage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Workpackage();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('wName')) {
                obj['wName'] = ApiClient.convertToType(data['wName'], 'String');
            }
            if (data.hasOwnProperty('wPMs')) {
                obj['wPMs'] = ApiClient.convertToType(data['wPMs'], 'String');
            }
            if (data.hasOwnProperty('wRole')) {
                obj['wRole'] = ApiClient.convertToType(data['wRole'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Workpackage.prototype['_id'] = undefined;

/**
 * @member {String} wName
 */
Workpackage.prototype['wName'] = undefined;

/**
 * @member {String} wPMs
 */
Workpackage.prototype['wPMs'] = undefined;

/**
 * @member {String} wRole
 */
Workpackage.prototype['wRole'] = undefined;






export default Workpackage;

