/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Wp model module.
 * @module model/Wp
 * @version 1.0.0
 */
class Wp {
    /**
     * Constructs a new <code>Wp</code>.
     * @alias module:model/Wp
     * @param wpname {String} 
     */
    constructor(wpname) { 
        
        Wp.initialize(this, wpname);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, wpname) { 
        obj['wpname'] = wpname;
    }

    /**
     * Constructs a <code>Wp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Wp} obj Optional instance to populate.
     * @return {module:model/Wp} The populated <code>Wp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Wp();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('wpname')) {
                obj['wpname'] = ApiClient.convertToType(data['wpname'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Wp.prototype['_id'] = undefined;

/**
 * @member {String} wpname
 */
Wp.prototype['wpname'] = undefined;






export default Wp;

